import React, {useEffect, useMemo, useState} from "react";
import {createRoot} from "react-dom/client";
import {questions, topics, tests} from "./data";
import "./styles.css";

const Icon=({children})=><span className="icon" aria-hidden="true">{children}</span>;
const ProgressBar=({value})=><div className="progress"><span style={{width:`${value}%`}}/></div>;
const Badge=({children,tone=""})=><span className={`badge ${tone}`}>{children}</span>;
const StatCard=({label,value,meta,icon})=><div className="stat-card"><div className="stat-icon">{icon}</div><div><div className="stat-label">{label}</div><div className="stat-value">{value}</div>{meta&&<div className="stat-meta">{meta}</div>}</div></div>;

function App(){
  const [page,setPage]=useState("home");
  const [dark,setDark]=useState(()=>localStorage.getItem("gate-theme")==="dark");
  const [bookmarks,setBookmarks]=useState(()=>JSON.parse(localStorage.getItem("gate-bookmarks")||"[]"));
  const [wrong,setWrong]=useState(()=>JSON.parse(localStorage.getItem("gate-wrong")||"[]"));
  const [activeQuestion,setActiveQuestion]=useState(0);
  const [answers,setAnswers]=useState({});
  const [submitted,setSubmitted]=useState(false);
  const [paletteOpen,setPaletteOpen]=useState(false);
  const [selectedTest,setSelectedTest]=useState(null);
  const [testRunning,setTestRunning]=useState(false);
  const [testFinished,setTestFinished]=useState(false);
  const [search,setSearch]=useState("");
  const [filters,setFilters]=useState({year:"All",topic:"All",type:"All",difficulty:"All"});
  const [mobileMenu,setMobileMenu]=useState(false);

  useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("gate-theme",dark?"dark":"light")},[dark]);
  useEffect(()=>localStorage.setItem("gate-bookmarks",JSON.stringify(bookmarks)),[bookmarks]);
  useEffect(()=>localStorage.setItem("gate-wrong",JSON.stringify(wrong)),[wrong]);

  const navigate=p=>{setPage(p);setMobileMenu(false);window.scrollTo({top:0,behavior:"smooth"})};
  const current=questions[activeQuestion % questions.length];
  const isBookmarked=bookmarks.includes(current.id);

  const filteredQuestions=useMemo(()=>questions.filter(q=>
    (filters.year==="All"||String(q.year)===filters.year)&&
    (filters.topic==="All"||q.topic===filters.topic)&&
    (filters.type==="All"||q.type===filters.type)&&
    (filters.difficulty==="All"||q.difficulty===filters.difficulty)&&
    (!search||`${q.topic} ${q.subtopic} ${q.question}`.toLowerCase().includes(search.toLowerCase()))
  ),[filters,search]);

  const toggleBookmark=()=>setBookmarks(b=>b.includes(current.id)?b.filter(x=>x!==current.id):[...b,current.id]);
  const chooseAnswer=a=>setAnswers(x=>({...x,[current.id]:a}));
  const submitAnswer=()=>{setSubmitted(true); if(!isCorrect(current,answers[current.id])) setWrong(w=>w.includes(current.id)?w:[...w,current.id])};
  const nextQuestion=()=>{setSubmitted(false);setActiveQuestion(i=>(i+1)%questions.length)};
  const openQuestion=(id)=>{const idx=questions.findIndex(q=>q.id===id);setActiveQuestion(Math.max(0,idx));setSubmitted(false);navigate("question")};
  const startTest=t=>{setSelectedTest(t);setTestRunning(false);setTestFinished(false);navigate("test-intro")};
  const beginTest=()=>{setTestRunning(true);setTestFinished(false);setActiveQuestion(0);setAnswers({});navigate("test")};
  const finishTest=()=>{setTestFinished(true);setTestRunning(false);navigate("result")};

  return <div className="app">
    <Sidebar page={page} navigate={navigate}/>
    <div className="shell">
      <Topbar search={search} setSearch={setSearch} dark={dark} setDark={setDark} onMenu={()=>setMobileMenu(true)} navigate={navigate}/>
      <main className="main">
        {page==="home"&&<Home navigate={navigate} openQuestion={openQuestion}/>}
        {page==="practice"&&<Practice navigate={navigate}/>}
        {page==="pyqs"&&<PYQs filters={filters} setFilters={setFilters} filtered={filteredQuestions} openQuestion={openQuestion} search={search}/>}
        {page==="question"&&<QuestionScreen q={current} answer={answers[current.id]} choose={chooseAnswer} submitted={submitted} submit={submitAnswer} next={nextQuestion} bookmarked={isBookmarked} bookmark={toggleBookmark} paletteOpen={paletteOpen} setPaletteOpen={setPaletteOpen} active={activeQuestion}/>}
        {page==="tests"&&<Tests startTest={startTest}/>}
        {page==="test-intro"&&<TestIntro test={selectedTest} begin={beginTest} back={()=>navigate("tests")}/>}
        {page==="test"&&testRunning&&<QuestionScreen q={current} answer={answers[current.id]} choose={chooseAnswer} submitted={submitted} submit={submitAnswer} next={nextQuestion} bookmarked={isBookmarked} bookmark={toggleBookmark} paletteOpen={paletteOpen} setPaletteOpen={setPaletteOpen} active={activeQuestion} testMode onFinish={finishTest}/>}
        {page==="result"&&<Result navigate={navigate}/>}
        {page==="predicted"&&<Predicted openQuestion={openQuestion}/>}
        {page==="progress"&&<Progress/>}
        {page==="bookmarks"&&<BookmarkPage ids={bookmarks} openQuestion={openQuestion} navigate={navigate}/>}
        {page==="wrong"&&<WrongPage ids={wrong} openQuestion={openQuestion} navigate={navigate}/>}
        {page==="profile"&&<Profile dark={dark} setDark={setDark}/>}
      </main>
      <BottomNav page={page} navigate={navigate}/>
    </div>
    {mobileMenu&&<MobileNav page={page} navigate={navigate} close={()=>setMobileMenu(false)}/>}
  </div>
}

function Sidebar({page,navigate}){
 const items=[["home","Dashboard","⌂"],["pyqs","PYQs","▣"],["practice","Practice","✦"],["tests","Mock Tests","◈"],["predicted","Predicted Questions","◆"],["bookmarks","Bookmarks","☆"],["wrong","Wrong Questions","!"],["progress","Progress","↗"],["profile","Profile","●"]];
 return <aside className="sidebar"><div className="brand"><div className="brand-mark">CH</div><div><strong>GATE CH</strong><small>Practice</small></div></div><nav>{items.map(([id,label,ic])=><button key={id} className={page===id?"active":""} onClick={()=>navigate(id)}><Icon>{ic}</Icon>{label}</button>)}</nav><div className="side-note"><b>Exam focus</b><span>GATE Chemical Engineering</span><Badge>2027</Badge></div></aside>
}
function BottomNav({page,navigate}){const items=[["home","Home","⌂"],["practice","Practice","✦"],["tests","Tests","◈"],["progress","Progress","↗"],["profile","Profile","●"]];return <nav className="bottom-nav">{items.map(([id,l,i])=><button key={id} className={page===id?"active":""} onClick={()=>navigate(id)}><Icon>{i}</Icon><span>{l}</span></button>)}</nav>}
function MobileNav({page,navigate,close}){return <div className="drawer-backdrop" onClick={close}><aside className="mobile-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><b>GATE CH Practice</b><button onClick={close}>×</button></div>{["home","pyqs","practice","tests","predicted","bookmarks","wrong","progress","profile"].map(id=><button key={id} className={page===id?"active":""} onClick={()=>navigate(id)}>{id.replace("-"," ")}</button>)}</aside></div>}
function Topbar({search,setSearch,dark,setDark,onMenu,navigate}){return <header className="topbar"><button className="menu-btn" onClick={onMenu}>☰</button><div className="mobile-title"><b>GATE CH</b><span>Practice</span></div><div className="search-wrap"><Icon>⌕</Icon><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search topics, concepts, questions…" onFocus={()=>navigate("pyqs")}/></div><button className="theme-btn" aria-label="Toggle dark mode" onClick={()=>setDark(x=>!x)}>{dark?"☀":"☾"}</button><button className="avatar" onClick={()=>navigate("profile")}>S</button></header>}

function PageTitle({eyebrow,title,subtitle,children}){return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{children}</div>}
function Home({navigate,openQuestion}){return <div>
 <PageTitle eyebrow="GATE CH • 2027" title="Good morning 👋" subtitle="Prepare smarter. Practice better."/>
 <section className="hero-card"><div><Badge tone="soft">Your preparation</Badge><h2>Build consistency, one question at a time.</h2><p>You're 78% through your demo preparation plan.</p><ProgressBar value={78}/><div className="hero-foot"><span>Overall Progress</span><b>78%</b></div></div><div className="hero-illustration">CH<span>+</span></div></section>
 <div className="stats-grid"><StatCard label="Questions Solved" value="324" meta="+18 this week" icon="✓"/><StatCard label="Accuracy" value="76%" meta="Last 30 days" icon="◎"/><StatCard label="Study Streak" value="7 Days" meta="Keep it going 🔥" icon="🔥"/></div>
 <SectionHead title="Continue Practice" action="View all" onClick={()=>navigate("practice")}/><div className="continue-card" onClick={()=>openQuestion(1)}><div className="subject-icon">MT</div><div className="grow"><b>Mass Transfer</b><span>12 questions remaining</span><ProgressBar value={62}/></div><button className="round-arrow">→</button></div>
 <SectionHead title="Today's Goal"/><div className="goal-card"><div className="goal-top"><div><b>20 Questions</b><span>14 / 20 completed</span></div><strong>70%</strong></div><ProgressBar value={70}/><button className="primary full" onClick={()=>navigate("practice")}>Continue Practice</button></div>
 <SectionHead title="Quick Practice"/><div className="quick-grid">{[["10","15 Minutes"],["25","30 Minutes"],["50","60 Minutes"]].map(x=><button className="quick-card" key={x[0]} onClick={()=>openQuestion(1)}><strong>{x[0]}</strong><span>Questions</span><small>{x[1]}</small></button>)}</div>
 <SectionHead title="Weak Topics" action="Practice" onClick={()=>navigate("practice")}/><div className="weak-list">{[["Mass Transfer",54],["Fluid Mechanics",61],["Thermodynamics",78]].map(([n,v])=><div className="weak-row" key={n}><div><b>{n}</b><span>{v}%</span></div><ProgressBar value={v}/></div>)}</div>
 <SectionHead title="Recent Activity"/><div className="activity"><div><span className="check">✓</span><div><b>Thermodynamics Test</b><small>Score: 16/20</small></div><time>Today</time></div><div><span className="check">✓</span><div><b>Mass Transfer PYQs</b><small>12/15 correct</small></div><time>Yesterday</time></div></div>
 </div>}
function SectionHead({title,action,onClick}){return <div className="section-head"><h2>{title}</h2>{action&&<button onClick={onClick}>{action} →</button>}</div>}
function Practice({navigate}){const cards=[["PYQs","Practice previous year GATE questions","▣","pyqs"],["Topic Practice","Practice questions from a specific subject","◎","pyqs"],["Predicted Questions","Pattern-based practice questions","◆","predicted"],["Daily Challenge","10 questions every day","⚡","question"]];return <div><PageTitle eyebrow="PRACTICE" title="Practice" subtitle="Choose how you want to practice."/><div className="practice-grid">{cards.map(([t,d,i,p])=><button className="practice-card" key={t} onClick={()=>navigate(p)}><span className="large-icon">{i}</span><div><h3>{t}</h3><p>{d}</p></div><span className="arrow">→</span></button>)}</div><div className="demo-banner"><b>Demo data</b><span>All questions in V1 are sample/demo questions and can be replaced with real PYQs later.</span></div></div>}
function FilterBar({filters,setFilters}){return <div className="filters"><select value={filters.year} onChange={e=>setFilters({...filters,year:e.target.value})}><option>All</option>{[2025,2024,2023,2022,2021].map(y=><option key={y}>{y}</option>)}</select><select value={filters.topic} onChange={e=>setFilters({...filters,topic:e.target.value})}><option>All</option>{topics.map(t=><option key={t}>{t}</option>)}</select><select value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option>All</option><option>MCQ</option><option>MSQ</option><option>NAT</option></select><select value={filters.difficulty} onChange={e=>setFilters({...filters,difficulty:e.target.value})}><option>All</option><option>Easy</option><option>Medium</option><option>Hard</option></select></div>}
function PYQs({filters,setFilters,filtered,openQuestion,search}){return <div><PageTitle eyebrow="QUESTION BANK" title="GATE CH Previous Year Questions" subtitle="250+ questions • Demo library for frontend V1"><Badge tone="soft">SAMPLE / DEMO</Badge></PageTitle><div className="filter-mobile"><span>{filtered.length} matching</span><button className="secondary">☷ Filters</button></div><FilterBar filters={filters} setFilters={setFilters}/><div className="question-list">{filtered.map((q,i)=><QuestionCard q={q} key={q.id} onClick={()=>openQuestion(q.id)}/>)}</div>{filtered.length===0&&<Empty title="No questions found" text="Try changing your filters or search term." action="Clear filters" onClick={()=>setFilters({year:"All",topic:"All",type:"All",difficulty:"All"})}/>}</div>}
function QuestionCard({q,onClick}){return <article className="q-card"><div className="q-meta"><Badge>GATE CH {q.year}</Badge><Badge tone="outline">{q.topic}</Badge><span>{q.type}</span><span>{q.marks} Marks</span></div><h3>Q. {q.id} <span>{q.question}</span></h3><div className="q-bottom"><Badge tone={q.difficulty.toLowerCase()}>{q.difficulty}</Badge><button className="secondary" onClick={onClick}>Practice →</button></div></article>}
function QuestionScreen({q,answer,choose,submitted,submit,next,bookmarked,bookmark,paletteOpen,setPaletteOpen,active,testMode,onFinish}){const correct=isCorrect(q,answer);return <div className="exam-wrap"><div className="exam-top"><button className="back-link" onClick={()=>history.back()}>← Back</button><div><b>{testMode?"GATE CH Full Mock":"GATE CH "+q.year}</b><span>Question {active+1} / 25</span></div><button className="timer">14:32</button></div><div className="exam-progress"><span style={{width:`${((active+1)/25)*100}%`}}/></div><div className="exam-body"><div className="exam-main"><div className="exam-tags"><Badge tone="soft">{q.topic}</Badge><Badge tone="outline">{q.type}</Badge><Badge tone={q.difficulty.toLowerCase()}>{q.difficulty}</Badge></div><h1 className="question-title">{q.question}</h1><div className="options">{q.type==="NAT"?<input className="nat-input" inputMode="decimal" value={answer||""} onChange={e=>choose(e.target.value)} placeholder="Enter numerical answer"/>:q.options.map(o=><button key={o} className={`option ${isSelected(q,answer,o)?"selected":""} ${submitted&&selectedCorrect(q,o)?"correct":""} ${submitted&&isSelected(q,answer,o)&&!selectedCorrect(q,o)?"wrong":""}`} onClick={()=>choose(q.type==="MSQ"?toggleMulti(answer,o):o)}><span className="radio">{q.type==="MSQ"?(answer||[]).includes(o)?"✓":"":isSelected(q,answer,o)?"●":""}</span>{o}</button>)}</div>{submitted&&<div className={`explanation ${correct?"success":"danger"}`}><div className="ex-head">{correct?"✓ Correct Answer":"× Review Answer"}</div><b>Correct Answer: {Array.isArray(q.correctAnswer)?q.correctAnswer.join(", "):q.correctAnswer}</b><p>{q.explanation}</p><div className="formula"><span>Formula</span>{q.formula}</div><div className="concept"><span>Concept</span>{q.concept}</div></div>}<div className="exam-actions">{!submitted?<><button className="secondary" onClick={()=>choose("")}>Clear</button><button className="secondary" onClick={bookmark}>{bookmarked?"★ Bookmarked":"☆ Mark for Review"}</button><button className="primary grow-btn" disabled={!answer} onClick={submit}>Submit & Next</button></>:<><button className="secondary" onClick={bookmark}>{bookmarked?"★ Bookmarked":"☆ Bookmark"}</button><button className="primary grow-btn" onClick={next}>Next Question →</button></>}</div>{testMode&&<button className="finish-test" onClick={onFinish}>Submit Test</button>}</div><aside className="palette"><div className="palette-head"><b>Question Palette</b><button onClick={()=>setPaletteOpen(!paletteOpen)}>☷</button></div><div className={`palette-grid ${paletteOpen?"open":""}`}>{Array.from({length:25},(_,i)=><button key={i} className={i===active?"current":i<4?"answered":""} onClick={()=>{setPaletteOpen(false)}}>{i+1}</button>)}</div><div className="palette-legend"><span><i className="answered-dot"/>Answered</span><span><i/>Unanswered</span><span><i className="current-dot"/>Current</span></div></aside></div></div>}
function selected(q,o){const a=window.__gateAnswer;return false} // unused helper retained for clarity
function isSelected(q,answer,o){return q.type==="MSQ"?(answer||[]).includes(o):answer===o}
function selectedCorrect(q,o){return q.type==="MSQ"?(q.correctAnswer||[]).includes(o):q.correctAnswer===o}
function isCorrect(q,a){if(q.type==="MSQ") return JSON.stringify([...(a||[])].sort())===JSON.stringify([...q.correctAnswer].sort()); return String(a||"").trim().toLowerCase()===String(q.correctAnswer).trim().toLowerCase()}
function toggleMulti(answer,o){const a=Array.isArray(answer)?answer:[];return a.includes(o)?a.filter(x=>x!==o):[...a,o]}
function TestCard({t,startTest}){return <article className="test-card"><div className="test-icon">◈</div><div className="grow"><Badge tone="soft">{t.kind}</Badge><h3>{t.title}</h3><div className="test-stats"><span>◉ {t.questions} Questions</span><span>◷ {t.duration}</span></div></div><button className="primary" onClick={()=>startTest(t)}>Start Test</button></article>}
function Tests({startTest}){return <div><PageTitle eyebrow="ASSESSMENT" title="Mock Tests" subtitle="Simulate the exam with focused demo tests."/><TestCard t={tests[0]} startTest={startTest}/><SectionHead title="Subject Tests"/><div className="test-list">{tests.slice(1).map(t=><TestCard key={t.id} t={t} startTest={startTest}/>)}</div></div>}
function TestIntro({test,begin,back}){if(!test)return <Empty title="No test selected" text="Choose a mock test first." action="Back to Tests" onClick={back}/>;return <div className="intro-card"><button className="back-link" onClick={back}>← Back to Mock Tests</button><div className="intro-icon">◈</div><Badge tone="soft">DEMO TEST</Badge><h1>{test.title}</h1><p>Clean exam-like practice using sample questions.</p><div className="intro-stats"><div><b>{test.questions}</b><span>Questions</span></div><div><b>{test.duration}</b><span>Duration</span></div><div><b>{test.marks}</b><span>Maximum Marks</span></div></div><div className="instructions"><h3>Important Instructions</h3><ul><li>MCQ, MSQ and NAT formats may appear.</li><li>Use the palette to move between questions.</li><li>This is a frontend demo; results use sample analytics.</li></ul></div><button className="primary full" onClick={begin}>Start Test</button></div>}
function Result({navigate}){return <div><PageTitle eyebrow="RESULT" title="Test Completed 🎉" subtitle="GATE CH Full Mock • Demo result"/><div className="result-hero"><div className="score-ring"><strong>62</strong><span>/ 100</span></div><div><h2>Solid practice session</h2><p>Review your weaker topics and repeat the concepts you missed.</p></div></div><div className="stats-grid four"><StatCard label="Accuracy" value="76%" icon="◎"/><StatCard label="Attempted" value="54 / 65" icon="✓"/><StatCard label="Correct" value="41" icon="+"/><StatCard label="Avg. Time" value="2m 18s" icon="◷"/></div><section className="panel"><SectionHead title="Topic Performance"/>{[["Thermodynamics",82],["Fluid Mechanics",68],["Mass Transfer",54],["Heat Transfer",79],["CRE",73]].map(([n,v])=><div className="perf-row" key={n}><div><b>{n}</b><span>{v}%</span></div><ProgressBar value={v}/></div>)}</section><div className="recommend"><div><Badge tone="soft">Recommended Next</Badge><h3>Practice Mass Transfer</h3><p>Focus on absorption, distillation and transfer-unit concepts.</p></div><button className="primary" onClick={()=>navigate("pyqs")}>Practice Now</button></div><div className="result-actions"><button className="secondary" onClick={()=>navigate("question")}>Review Test</button><button className="primary" onClick={()=>navigate("home")}>Back to Dashboard</button></div></div>}
function Predicted({openQuestion}){return <div><PageTitle eyebrow="PRACTICE SETS" title="Predicted Questions" subtitle="Pattern-based practice for revision."/><div className="notice">ⓘ <span>These are practice questions based on syllabus coverage and historical patterns. They are <b>NOT guaranteed predictions</b> of the actual GATE paper.</span></div><div className="pred-grid">{[["Mass Transfer",5,"High"],["Thermodynamics",5,"High"],["Reaction Engineering",5,"Medium"],["Fluid Mechanics",5,"Medium"]].map(([n,c,d],i)=><article className="pred-card" key={n}><div><Badge tone="soft">High Priority Practice</Badge><h3>{n}</h3><p>{c} Questions</p></div><Badge tone={d.toLowerCase()}>{d}</Badge><button className="secondary" onClick={()=>openQuestion(i+1)}>Practice →</button></article>)}</div></div>}
function Progress(){return <div><PageTitle eyebrow="ANALYTICS" title="Your Progress" subtitle="A demo view of your preparation trends."/><div className="stats-grid four"><StatCard label="Questions Solved" value="324" icon="✓"/><StatCard label="Accuracy" value="76%" icon="◎"/><StatCard label="Study Time" value="18h 42m" icon="◷"/><StatCard label="Current Streak" value="7 days" icon="🔥"/></div><div className="chart-grid"><Chart title="Accuracy Over Time" values={[58,63,61,68,72,70,76]}/><Chart title="Questions Solved" values={[24,42,31,55,48,61,73]}/><Chart title="Mock Test Scores" values={[52,58,64,59,62]}/></div><section className="panel"><SectionHead title="Subject Performance"/>{[["Thermodynamics",82],["Fluid Mechanics",68],["Mass Transfer",54],["Heat Transfer",79]].map(([n,v])=><div className="perf-row" key={n}><div><b>{n}</b><span>{v}%</span></div><ProgressBar value={v}/></div>)}</section><section className="focus"><h2>Focus Areas</h2><Badge tone="medium">Mass Transfer</Badge><Badge tone="medium">Fluid Mechanics</Badge></section></div>}
function Chart({title,values}){const max=Math.max(...values);return <section className="panel chart"><h3>{title}</h3><div className="bars">{values.map((v,i)=><div key={i} style={{height:`${(v/max)*100}%`}}><span>{v}</span></div>)}</div><div className="chart-labels">{values.map((_,i)=><span key={i}>W{i+1}</span>)}</div></section>}
function BookmarkPage({ids,openQuestion,navigate}){const qs=questions.filter(q=>ids.includes(q.id));return <div><PageTitle eyebrow="SAVED" title="Bookmarked Questions" subtitle="Questions you want to revisit."/><div className="tabs"><button className="active">All</button><button>PYQs</button><button>Practice</button><button>Mock Tests</button></div>{qs.length?qs.map(q=><QuestionCard q={q} key={q.id} onClick={()=>openQuestion(q.id)}/>):<Empty title="No bookmarked questions yet." text="Questions you bookmark will appear here." action="Explore PYQs" onClick={()=>navigate("pyqs")}/>}</div>}
function WrongPage({ids,openQuestion,navigate}){const qs=questions.filter(q=>ids.includes(q.id));return <div><PageTitle eyebrow="REVIEW" title="My Mistakes" subtitle="Questions you got wrong — practice them again."/><div className="mistake-count"><b>{qs.length||13}</b> Questions</div><div className="tabs"><button className="active">All</button><button>Concept Mistake</button><button>Calculation Mistake</button><button>Silly Mistake</button></div>{qs.length?qs.map(q=><article className="q-card" key={q.id}><div className="q-meta"><Badge>{q.topic}</Badge><Badge tone="outline">GATE CH {q.year}</Badge><span>Incorrect previously</span></div><h3>{q.question}</h3><button className="secondary" onClick={()=>openQuestion(q.id)}>Practice Again</button></article>):<Empty title="No wrong questions yet." text="Once you miss a demo question, it will appear here." action="Practice" onClick={()=>navigate("practice")}/>}</div>}
function Profile({dark,setDark}){return <div><PageTitle eyebrow="ACCOUNT" title="Profile" subtitle="Your demo preparation profile."/><section className="profile-card"><div className="profile-avatar">S</div><div><h2>Sohan</h2><p>GATE Chemical Engineering</p><Badge tone="soft">Target: GATE 2027</Badge></div></section><div className="stats-grid four"><StatCard label="Questions Solved" value="324" icon="✓"/><StatCard label="Accuracy" value="76%" icon="◎"/><StatCard label="7 Day Streak" value="7" icon="🔥"/><StatCard label="Tests Completed" value="12" icon="◈"/></div><section className="settings panel"><h2>Settings</h2><label><span>Dark Mode<small>Use a comfortable dark theme</small></span><input type="checkbox" checked={dark} onChange={e=>setDark(e.target.checked)}/></label><label><span>Notifications<small>Demo preference</small></span><input type="checkbox" defaultChecked/></label><button>Question Preferences <span>→</span></button><button>About <span>→</span></button></section></div>}
function Empty({title,text,action,onClick}){return <div className="empty"><div className="empty-icon">○</div><h3>{title}</h3><p>{text}</p>{action&&<button className="primary" onClick={onClick}>{action}</button>}</div>}

createRoot(document.getElementById("root")).render(<App/>);
